name: Deploy

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'
      - '[0-9].[0-9].[0-9]-rc[0-9]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: run echo
        run: echo ${{ github.ref_name }}
